<?php
/**
 *  Copyright © 2019-2020 Developer, Ltd. All rights reserved.
 *
 *  Override checkout page from parent theme
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?php /* @escapeNotVerified */ echo json_encode($block->getCheckoutConfig(), JSON_HEX_TAG); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>

<!-- Jquery to display the custom message after selection of "United Arab emirates" -->
<script type="text/javascript">
 require(["jquery"], function($) {
        
    $(document).on("change",'select[name="country_id"]', function(){                 
      var selectedCountry = $(this).children("option:selected").val();       
            if(selectedCountry == "AE"){
                $( 'div[name="shippingAddress.country_id"]' ).append( '<div class="alert_sucess"> "United Arab Emirates" is selected </div>' );
            }
            else{
                $( 'div[name="shippingAddress.country_id"] .alert_sucess' ).hide();
            }
    });
});


</script>